### ISSUE TITLE
Non Zero Min Values

### ISSUE THREAD

**Issue by eblabs** [rsgalloway/QRangeSlider#2]
Hi Ryan,

Really nice work on this! Ive just run into a bit of a bug though. The min setting only seems to work properly when set to zero. So setting a min and max to something like 1000-5000 doesnt draw the range correctly.

Would you mind checking this out?

Thanks again, this is almost perfect!!

Eric

**Comment by rsgalloway** [comment]
Hey Eric, thanks for the kind words. I think I have fixed this issue, please give it a try.

**Comment by eblabs** [comment]
Thanks for the very fast reply. Ill give this a try first thing monday morning!

**Comment by eblabs** [comment]
Just added your new code. Works perfectly, thanks so much!

**Comment by rsgalloway** [comment]
Great!
